apply plugin: 'com.android.application'

android {
    compileSdkVersion 30

    defaultConfig {
        applicationId 'com.shir.stems'
        minSdkVersion 19
        targetSdkVersion 19
        versionCode 2
        versionName '0.2.0'
        ndkVersion '21.4.7075529'

        ndk {
            abiFilters 'armeabi-v7a', 'x86'
        }

        externalNativeBuild {
            cmake {
                cppFlags "-std=c++17 -O3"
                arguments "-DANDROID_PLATFORM=android-19"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
            version "3.18.1"
        }
    }

    aaptOptions {
        noCompress 'bin'
    }

    lintOptions {
        abortOnError false
    }
}
